require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Property = require('../models/Property');
const Developer = require('../models/Developer');
const Agent = require('../models/Agent');
const BlogPost = require('../models/BlogPost');
const User = require('../models/User');

const IMG = 'https://media.istockphoto.com/id/2175808798/photo/houses-on-palm-island-in-dubai.jpg?s=612x612&w=0&k=20&c=IS-sQ8O8luKFilHBfjiJLa4e0Q0vYXopk9YDI4F05Q8=';

async function seed() {
    await connectDB();
    console.log('Clearing existing data...');
    await Promise.all([
        Property.deleteMany({}),
        Developer.deleteMany({}),
        Agent.deleteMany({}),
        BlogPost.deleteMany({}),
        User.deleteMany({}),
    ]);

    // --- Admin User ---
    const admin = await User.create({
        email: 'admin@realcapital.ae',
        password: 'admin123',
    });
    console.log('Admin created:', admin.email);

    // --- Developers ---
    const developers = await Developer.insertMany([
        { name: 'EMAAR Properties', slug: 'emaar', logo: IMG, description: 'Emaar Properties is one of the largest real estate developers in the UAE, known for iconic projects like Burj Khalifa and Dubai Mall.', projectsCount: 60, website: 'https://www.emaar.com' },
        { name: 'DAMAC Properties', slug: 'damac', logo: IMG, description: 'DAMAC Properties has delivered over 43,000 homes across the Middle East, with luxury branded residences.', projectsCount: 45, website: 'https://www.damacproperties.com' },
        { name: 'MERAAS', slug: 'meraas', logo: IMG, description: 'Meraas is a Dubai-based holding company that creates destinations and experiences across hospitality, retail, and real estate.', projectsCount: 25, website: 'https://www.meraas.com' },
        { name: 'BINGHATTI', slug: 'binghatti', logo: IMG, description: 'Binghatti Developers is an award-winning Emirati real estate developer known for contemporary Islamic architecture.', projectsCount: 35, website: 'https://www.binghatti.com' },
        { name: 'NAKHEEL', slug: 'nakheel', logo: IMG, description: 'Nakheel is the master developer behind iconic projects like Palm Jumeirah and The World Islands.', projectsCount: 30, website: 'https://www.nakheel.com' },
    ]);
    console.log(`${developers.length} developers created`);

    // --- Agents ---
    const agents = await Agent.create([
        { name: 'Youssef Kamal', email: 'youssef@realcapital.ae', password: 'agent123', photo: IMG, phone: '+971 50 123 4567', languages: ['English', 'Arabic'], specialization: 'Luxury Villas', bio: 'Senior real estate consultant with 8+ years of experience in Dubai luxury market.', isApproved: true },
        { name: 'Nashrah Kamali', email: 'nashrah@realcapital.ae', password: 'agent123', photo: IMG, phone: '+971 50 234 5678', languages: ['English', 'Arabic', 'Hindi'], specialization: 'Off-Plan Apartments', bio: 'Specialist in off-plan investments and new project launches across Dubai.', isApproved: true },
        { name: 'David Chen', email: 'david@realcapital.ae', password: 'agent123', photo: IMG, phone: '+971 50 345 6789', languages: ['English', 'Mandarin'], specialization: 'Commercial Properties', bio: 'Expert in commercial real estate and investment properties for international clients.', isApproved: true },
    ]);
    console.log(`${agents.length} agents created`);

    // --- Properties (all 26 types, varied prices & statuses) ---
    const properties = await Property.insertMany([
        // ===== APARTMENTS =====
        { title: 'Creek Waters Residence', slug: 'creek-waters-residence', description: 'Stunning waterfront apartment at Dubai Creek Harbour with breathtaking views.', price: 1800000, priceLabel: 'AED 1.8M', location: { area: 'Dubai Creek Harbour', emirate: 'Dubai' }, propertyType: 'apartment', bedrooms: 2, bathrooms: 2, squareFt: 1400, completionYear: '2026', completionStatus: 'off-plan', paymentPlan: { downPayment: 20, onCompletion: 40, description: '20/40/40' }, developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Concierge', 'Parking'], status: 'for-sale', isFeatured: true },
        { title: 'Marina Heights Tower', slug: 'marina-heights-tower', description: 'Premium 3-bed apartment in Dubai Marina with stunning marina and sea views.', price: 3500000, priceLabel: 'AED 3.5M', location: { area: 'Dubai Marina', emirate: 'Dubai' }, propertyType: 'apartment', bedrooms: 3, bathrooms: 3, squareFt: 2100, completionYear: '2024', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Beach Access', 'Valet'], status: 'for-sale', isFeatured: true },
        { title: 'JBR Luxury Apartment Rental', slug: 'jbr-luxury-apartment-rental', description: 'Fully furnished 2-bed apartment for rent in JBR with full sea views.', price: 180000, priceLabel: 'AED 180K/yr', location: { area: 'JBR', emirate: 'Dubai' }, propertyType: 'apartment', bedrooms: 2, bathrooms: 2, squareFt: 1300, completionYear: '2020', completionStatus: 'ready-to-move', developer: developers[4]._id, agent: agents[2]._id, images: [IMG], amenities: ['Beach Access', 'Pool', 'Gym', 'Spa'], status: 'for-rent', isFeatured: false },

        // ===== PENTHOUSES =====
        { title: 'Mercedes Benz Places Penthouse', slug: 'mercedes-benz-places', description: 'Ultra-luxury branded penthouse by Mercedes Benz in Downtown Dubai.', price: 8800000, priceLabel: 'AED 8.8M', location: { area: 'Downtown Dubai', emirate: 'Dubai' }, propertyType: 'penthouse', bedrooms: 3, bathrooms: 4, squareFt: 4500, completionYear: '2028', completionStatus: 'off-plan', paymentPlan: { downPayment: 10, onCompletion: 50, description: '10/40/50' }, developer: developers[3]._id, agent: agents[2]._id, images: [IMG], amenities: ['Private Elevator', 'Rooftop Terrace', 'Infinity Pool', 'Butler Service'], status: 'for-sale', isFeatured: true },
        { title: 'Bugatti Residences Penthouse', slug: 'bugatti-residences', description: 'Exclusive Bugatti-branded penthouse featuring car elevators and bespoke interiors.', price: 19000000, priceLabel: 'AED 19M', location: { area: 'Business Bay', emirate: 'Dubai' }, propertyType: 'penthouse', bedrooms: 4, bathrooms: 5, squareFt: 7000, completionYear: '2028', completionStatus: 'off-plan', paymentPlan: { downPayment: 15, onCompletion: 50, description: '15/35/50' }, developer: developers[3]._id, agent: agents[0]._id, images: [IMG], amenities: ['Car Elevator', 'Private Pool', 'Cinema', 'Helipad'], status: 'for-sale', isFeatured: true },
        { title: 'Atlantis Penthouse Rental', slug: 'atlantis-penthouse-rental', description: 'Iconic penthouse for rent at Atlantis The Royal with panoramic ocean views.', price: 950000, priceLabel: 'AED 950K/yr', location: { area: 'Palm Jumeirah', emirate: 'Dubai' }, propertyType: 'penthouse', bedrooms: 3, bathrooms: 3, squareFt: 3800, completionYear: '2023', completionStatus: 'ready-to-move', developer: developers[4]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Spa', 'Concierge', 'Beach'], status: 'for-rent', isFeatured: false },

        // ===== VILLAS =====
        { title: 'The Oasis Branded Villas', slug: 'the-oasis-branded-villas', description: 'Ultra-luxury branded villa in Dubailand by Emaar with private pool.', price: 12000000, priceLabel: 'AED 12M', location: { area: 'Dubailand', emirate: 'Dubai' }, propertyType: 'villa', bedrooms: 4, bathrooms: 5, squareFt: 8250, completionYear: '2027', completionStatus: 'off-plan', paymentPlan: { downPayment: 20, onCompletion: 50, description: '20/30/50' }, developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Private Pool', 'Garden', 'Gym', 'Garage'], status: 'for-sale', isFeatured: true },
        { title: 'Palm Jumeirah Signature Villa', slug: 'palm-jumeirah-signature-villa', description: 'Exclusive beachfront villa on Palm Jumeirah frond with private beach.', price: 25000000, priceLabel: 'AED 25M', location: { area: 'Palm Jumeirah', emirate: 'Dubai' }, propertyType: 'villa', bedrooms: 6, bathrooms: 7, squareFt: 12000, completionYear: '2023', completionStatus: 'ready-to-move', developer: developers[4]._id, agent: agents[2]._id, images: [IMG], amenities: ['Private Beach', 'Pool', 'Cinema', 'Wine Cellar'], status: 'for-sale', isFeatured: true },
        { title: 'Al Barari Villa Rental', slug: 'al-barari-villa-rental', description: 'Lush green villa for rent in Al Barari botanical community with private pool.', price: 650000, priceLabel: 'AED 650K/yr', location: { area: 'Al Barari', emirate: 'Dubai' }, propertyType: 'villa', bedrooms: 5, bathrooms: 6, squareFt: 7500, completionYear: '2018', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[0]._id, images: [IMG], amenities: ['Private Pool', 'Garden', 'Spa', 'Gym'], status: 'for-rent', isFeatured: false },

        // ===== DUPLEXES =====
        { title: 'Bluewaters Island Duplex', slug: 'bluewaters-island-duplex', description: 'Spacious duplex on Bluewaters Island with Ain Dubai views and beach access.', price: 4800000, priceLabel: 'AED 4.8M', location: { area: 'Bluewaters Island', emirate: 'Dubai' }, propertyType: 'duplex', bedrooms: 3, bathrooms: 4, squareFt: 2800, completionYear: '2024', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[1]._id, images: [IMG], amenities: ['Beach', 'Pool', 'Gym', 'Retail'], status: 'for-sale', isFeatured: true },
        { title: 'DIFC Duplex Rental', slug: 'difc-duplex-rental', description: 'Modern duplex for rent in DIFC with skyline views and premium finishes.', price: 280000, priceLabel: 'AED 280K/yr', location: { area: 'DIFC', emirate: 'Dubai' }, propertyType: 'duplex', bedrooms: 2, bathrooms: 3, squareFt: 2200, completionYear: '2021', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Concierge'], status: 'for-rent', isFeatured: false },

        // ===== TOWNHOUSES =====
        { title: 'Damac Islands Phase II', slug: 'damac-islands-phase-ii', description: 'Modern island-style townhouse with waterfront views and Mediterranean design.', price: 2300000, priceLabel: 'AED 2.3M', location: { area: 'Damac Islands', emirate: 'Dubai' }, propertyType: 'townhouse', bedrooms: 4, bathrooms: 4, squareFt: 2208, completionYear: '2027', completionStatus: 'off-plan', paymentPlan: { downPayment: 20, onCompletion: 40, description: '20/40/40' }, developer: developers[1]._id, agent: agents[0]._id, images: [IMG], amenities: ['Pool', 'Garden', 'Gym', 'Marina'], status: 'for-sale', isFeatured: true },
        { title: 'Arabian Ranches Townhome', slug: 'arabian-ranches-townhome', description: 'Family-friendly townhouse in Arabian Ranches with mature landscaping.', price: 1900000, priceLabel: 'AED 1.9M', location: { area: 'Arabian Ranches', emirate: 'Dubai' }, propertyType: 'townhouse', bedrooms: 3, bathrooms: 3, squareFt: 1800, completionYear: '2022', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Park', 'School'], status: 'for-sale', isFeatured: false },

        // ===== STUDIOS =====
        { title: 'JVC Smart Studio', slug: 'jvc-smart-studio', description: 'Affordable smart-home studio in JVC. Strong rental yield potential.', price: 550000, priceLabel: 'AED 550K', location: { area: 'Jumeirah Village Circle', emirate: 'Dubai' }, propertyType: 'studio', bedrooms: 0, bathrooms: 1, squareFt: 450, completionYear: '2025', completionStatus: 'ready-to-move', developer: developers[3]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Smart Home'], status: 'for-sale', isFeatured: false },
        { title: 'Marina Walk Studio Rental', slug: 'marina-walk-studio-rental', description: 'Furnished studio for rent in Dubai Marina near metro and beach.', price: 75000, priceLabel: 'AED 75K/yr', location: { area: 'Dubai Marina', emirate: 'Dubai' }, propertyType: 'studio', bedrooms: 0, bathrooms: 1, squareFt: 500, completionYear: '2019', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Beach Access'], status: 'for-rent', isFeatured: false },

        // ===== PLOTS =====
        { title: 'Tilal Al Ghaf Premium Plot', slug: 'tilal-al-ghaf-premium-plot', description: 'Premium residential plot in Tilal Al Ghaf. Build your dream home.', price: 5500000, priceLabel: 'AED 5.5M', location: { area: 'Tilal Al Ghaf', emirate: 'Dubai' }, propertyType: 'plot', bedrooms: 0, bathrooms: 0, squareFt: 10000, completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[2]._id, images: [IMG], amenities: ['Community Pool', 'Park', 'School'], status: 'for-sale', isFeatured: false },
        { title: 'Saadiyat Island Beachfront Plot', slug: 'saadiyat-island-beachfront-plot', description: 'Rare beachfront plot on Saadiyat Island, Abu Dhabi with pristine beach access.', price: 8500000, priceLabel: 'AED 8.5M', location: { area: 'Saadiyat Island', emirate: 'Abu Dhabi' }, propertyType: 'plot', bedrooms: 0, bathrooms: 0, squareFt: 15000, completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[0]._id, images: [IMG], amenities: ['Beach Access', 'Park'], status: 'for-sale', isFeatured: true },

        // ===== MANSIONS =====
        { title: 'Emirates Hills Royal Mansion', slug: 'emirates-hills-royal-mansion', description: 'Palatial mansion overlooking Montgomerie Golf Course. Ultimate luxury.', price: 45000000, priceLabel: 'AED 45M', location: { area: 'Emirates Hills', emirate: 'Dubai' }, propertyType: 'mansion', bedrooms: 8, bathrooms: 10, squareFt: 20000, completionYear: '2021', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Pool', 'Tennis Court', 'Golf View', 'Cinema', 'Wine Cellar'], status: 'for-sale', isFeatured: true },
        { title: 'Al Ain Grand Mansion', slug: 'al-ain-grand-mansion', description: 'Sprawling mansion in Al Ain with mountain views and private grounds.', price: 18000000, priceLabel: 'AED 18M', location: { area: 'Al Ain', emirate: 'Abu Dhabi' }, propertyType: 'mansion', bedrooms: 7, bathrooms: 8, squareFt: 16000, completionYear: '2020', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Garden', 'Staff Quarters', 'Gym'], status: 'for-sale', isFeatured: false },

        // ===== HOTEL APARTMENTS =====
        { title: 'Address Dubai Mall Hotel Apt', slug: 'address-dubai-mall-hotel-apt', description: 'Luxury hotel apartment at Address Dubai Mall with 5-star services and Burj Khalifa views.', price: 2800000, priceLabel: 'AED 2.8M', location: { area: 'Downtown Dubai', emirate: 'Dubai' }, propertyType: 'hotel-apartment', bedrooms: 1, bathrooms: 1, squareFt: 900, completionYear: '2023', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Room Service', 'Pool', 'Spa', 'Concierge', 'Valet'], status: 'for-sale', isFeatured: true },
        { title: 'Palm Jumeirah Hotel Apt Rental', slug: 'palm-hotel-apt-rental', description: 'Furnished hotel apartment for rent on Palm Jumeirah with beach and pool access.', price: 120000, priceLabel: 'AED 120K/yr', location: { area: 'Palm Jumeirah', emirate: 'Dubai' }, propertyType: 'hotel-apartment', bedrooms: 1, bathrooms: 1, squareFt: 750, completionYear: '2019', completionStatus: 'ready-to-move', developer: developers[4]._id, agent: agents[1]._id, images: [IMG], amenities: ['Beach', 'Pool', 'Room Service', 'Gym'], status: 'for-rent', isFeatured: false },

        // ===== SKY VILLAS =====
        { title: 'Dorchester Sky Villa', slug: 'dorchester-sky-villa', description: 'Ultra-exclusive sky villa at Dorchester Collection in Business Bay with private terrace garden.', price: 35000000, priceLabel: 'AED 35M', location: { area: 'Business Bay', emirate: 'Dubai' }, propertyType: 'sky-villa', bedrooms: 5, bathrooms: 6, squareFt: 9500, completionYear: '2027', completionStatus: 'off-plan', paymentPlan: { downPayment: 25, onCompletion: 45, description: '25/30/45' }, developer: developers[1]._id, agent: agents[0]._id, images: [IMG], amenities: ['Private Pool', 'Terrace Garden', 'Butler', 'Gym'], status: 'for-sale', isFeatured: true },
        { title: 'Jumeirah Living Sky Villa', slug: 'jumeirah-living-sky-villa', description: 'Branded sky villa in Jumeirah Living with full Dubai skyline panorama.', price: 22000000, priceLabel: 'AED 22M', location: { area: 'JLT', emirate: 'Dubai' }, propertyType: 'sky-villa', bedrooms: 4, bathrooms: 5, squareFt: 7200, completionYear: '2026', completionStatus: 'off-plan', paymentPlan: { downPayment: 20, onCompletion: 40, description: '20/40/40' }, developer: developers[0]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Concierge', 'Sky Lounge'], status: 'for-sale', isFeatured: false },

        // ===== FULL FLOOR =====
        { title: 'Burj Khalifa Full Floor', slug: 'burj-khalifa-full-floor', description: 'Entire floor in the iconic Burj Khalifa. The most prestigious address in the world.', price: 65000000, priceLabel: 'AED 65M', location: { area: 'Downtown Dubai', emirate: 'Dubai' }, propertyType: 'full-floor', bedrooms: 5, bathrooms: 6, squareFt: 11000, completionYear: '2010', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Concierge', 'Observation Deck Access'], status: 'for-sale', isFeatured: true },
        { title: 'DIFC Full Floor Rental', slug: 'difc-full-floor-rental', description: 'Full floor residential in DIFC Gate District with 360° city views.', price: 850000, priceLabel: 'AED 850K/yr', location: { area: 'DIFC', emirate: 'Dubai' }, propertyType: 'full-floor', bedrooms: 4, bathrooms: 4, squareFt: 6500, completionYear: '2015', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Valet', 'Lounge'], status: 'for-rent', isFeatured: false },

        // ===== HALF FLOOR =====
        { title: 'Marina Gate Half Floor', slug: 'marina-gate-half-floor', description: 'Half-floor residence in Marina Gate with panoramic marina and sea views.', price: 7500000, priceLabel: 'AED 7.5M', location: { area: 'Dubai Marina', emirate: 'Dubai' }, propertyType: 'half-floor', bedrooms: 3, bathrooms: 4, squareFt: 3800, completionYear: '2022', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Concierge', 'Valet'], status: 'for-sale', isFeatured: false },

        // ===== PREMIUM VILLAS =====
        { title: 'Al Furjan Premium Villa', slug: 'al-furjan-premium-villa', description: 'Premium villa in Al Furjan with upgraded finishes, private pool and landscaped garden.', price: 3800000, priceLabel: 'AED 3.8M', location: { area: 'Al Furjan', emirate: 'Dubai' }, propertyType: 'premium-villa', bedrooms: 5, bathrooms: 5, squareFt: 4500, completionYear: '2024', completionStatus: 'ready-to-move', developer: developers[1]._id, agent: agents[0]._id, images: [IMG], amenities: ['Private Pool', 'Garden', 'Gym', 'Maid Room'], status: 'for-sale', isFeatured: true },
        { title: 'Yas Acres Premium Villa', slug: 'yas-acres-premium-villa', description: 'Premium villa on Yas Island Abu Dhabi with golf course views.', price: 4200000, priceLabel: 'AED 4.2M', location: { area: 'Yas Island', emirate: 'Abu Dhabi' }, propertyType: 'premium-villa', bedrooms: 4, bathrooms: 5, squareFt: 3900, completionYear: '2023', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Golf View', 'Garden', 'Gym'], status: 'for-sale', isFeatured: false },

        // ===== APARTMENT WITH PRIVATE POOL =====
        { title: 'One Za\'abeel Pool Apt', slug: 'one-zaabeel-pool-apt', description: 'Luxury apartment with private plunge pool at One Za\'abeel linked towers.', price: 6500000, priceLabel: 'AED 6.5M', location: { area: 'Za\'abeel', emirate: 'Dubai' }, propertyType: 'apartment-private-pool', bedrooms: 2, bathrooms: 3, squareFt: 2200, completionYear: '2025', completionStatus: 'ready-to-move', developer: developers[4]._id, agent: agents[0]._id, images: [IMG], amenities: ['Private Pool', 'Gym', 'Spa', 'Sky Lounge'], status: 'for-sale', isFeatured: true },

        // ===== STUDIO WITH POOL =====
        { title: 'Meydan Studio with Pool', slug: 'meydan-studio-pool', description: 'Stylish studio with shared rooftop pool in Meydan community. High ROI.', price: 650000, priceLabel: 'AED 650K', location: { area: 'Meydan', emirate: 'Dubai' }, propertyType: 'studio-pool', bedrooms: 0, bathrooms: 1, squareFt: 520, completionYear: '2026', completionStatus: 'off-plan', paymentPlan: { downPayment: 10, onCompletion: 40, description: '10/50/40' }, developer: developers[1]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Café'], status: 'for-sale', isFeatured: false },
        { title: 'Sports City Studio Pool Rental', slug: 'sports-city-studio-pool-rental', description: 'Furnished studio with pool access for rent in Dubai Sports City.', price: 45000, priceLabel: 'AED 45K/yr', location: { area: 'Sports City', emirate: 'Dubai' }, propertyType: 'studio-pool', bedrooms: 0, bathrooms: 1, squareFt: 480, completionYear: '2017', completionStatus: 'ready-to-move', developer: developers[1]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Sports Facilities'], status: 'for-rent', isFeatured: false },

        // ===== SIMPLEX SEA VIEWS =====
        { title: 'La Mer Simplex Sea View', slug: 'la-mer-simplex-sea-view', description: 'Single-level simplex with unobstructed Arabian Gulf views at La Mer.', price: 5200000, priceLabel: 'AED 5.2M', location: { area: 'La Mer', emirate: 'Dubai' }, propertyType: 'simplex-sea-views', bedrooms: 2, bathrooms: 2, squareFt: 1800, completionYear: '2024', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[0]._id, images: [IMG], amenities: ['Beach Access', 'Pool', 'Retail', 'Dining'], status: 'for-sale', isFeatured: true },

        // ===== TWIN VILLAS =====
        { title: 'Mudon Twin Villa', slug: 'mudon-twin-villa', description: 'Semi-detached twin villa in Mudon community with shared wall concept.', price: 2600000, priceLabel: 'AED 2.6M', location: { area: 'Mudon', emirate: 'Dubai' }, propertyType: 'twin-villa', bedrooms: 4, bathrooms: 4, squareFt: 2800, completionYear: '2025', completionStatus: 'ready-to-move', developer: developers[1]._id, agent: agents[1]._id, images: [IMG], amenities: ['Community Pool', 'Park', 'School', 'Mosque'], status: 'for-sale', isFeatured: false },
        { title: 'Sharjah Sustainable Twin Villa', slug: 'sharjah-sustainable-twin-villa', description: 'Eco-friendly twin villa in Sharjah Sustainable City with solar power.', price: 1800000, priceLabel: 'AED 1.8M', location: { area: 'Sustainable City', emirate: 'Sharjah' }, propertyType: 'twin-villa', bedrooms: 3, bathrooms: 3, squareFt: 2200, completionYear: '2026', completionStatus: 'off-plan', paymentPlan: { downPayment: 15, onCompletion: 40, description: '15/45/40' }, developer: developers[1]._id, agent: agents[2]._id, images: [IMG], amenities: ['Solar Panels', 'EV Charging', 'Farm', 'Pool'], status: 'for-sale', isFeatured: false },

        // ===== STANDALONE VILLAS =====
        { title: 'Jumeirah Golf Estates Standalone', slug: 'jumeirah-golf-estates-standalone', description: 'Exclusive standalone villa in Jumeirah Golf Estates with golf course frontage.', price: 9500000, priceLabel: 'AED 9.5M', location: { area: 'Jumeirah Golf Estates', emirate: 'Dubai' }, propertyType: 'standalone-villa', bedrooms: 5, bathrooms: 6, squareFt: 6500, completionYear: '2022', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Pool', 'Golf View', 'Garden', 'Gym', 'Staff Quarters'], status: 'for-sale', isFeatured: true },
        { title: 'RAK Beachfront Standalone', slug: 'rak-beachfront-standalone', description: 'Beachfront standalone villa in Ras Al Khaimah with private beach.', price: 3200000, priceLabel: 'AED 3.2M', location: { area: 'Al Marjan Island', emirate: 'Ras Al Khaimah' }, propertyType: 'standalone-villa', bedrooms: 4, bathrooms: 4, squareFt: 3500, completionYear: '2027', completionStatus: 'off-plan', paymentPlan: { downPayment: 10, onCompletion: 50, description: '10/40/50' }, developer: developers[4]._id, agent: agents[1]._id, images: [IMG], amenities: ['Private Beach', 'Pool', 'Garden'], status: 'for-sale', isFeatured: false },

        // ===== DUPLEX + MAID =====
        { title: 'City Walk Duplex + Maid', slug: 'city-walk-duplex-maid', description: 'Spacious duplex with dedicated maid room in the vibrant City Walk community.', price: 3900000, priceLabel: 'AED 3.9M', location: { area: 'City Walk', emirate: 'Dubai' }, propertyType: 'duplex-maid', bedrooms: 3, bathrooms: 4, squareFt: 2600, completionYear: '2023', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[0]._id, images: [IMG], amenities: ['Pool', 'Retail', 'Gym', 'Maid Room'], status: 'for-sale', isFeatured: false },
        { title: 'Creek Harbour Duplex + Maid Rental', slug: 'creek-harbour-duplex-maid-rental', description: 'Furnished duplex with maid room for rent at Dubai Creek Harbour.', price: 220000, priceLabel: 'AED 220K/yr', location: { area: 'Dubai Creek Harbour', emirate: 'Dubai' }, propertyType: 'duplex-maid', bedrooms: 3, bathrooms: 3, squareFt: 2400, completionYear: '2022', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Creek View', 'Maid Room'], status: 'for-rent', isFeatured: false },

        // ===== APARTMENT + MAID =====
        { title: 'Downtown Boulevard Apt + Maid', slug: 'downtown-boulevard-apt-maid', description: 'Premium apartment with maid room on Downtown Boulevard facing Burj Khalifa.', price: 4500000, priceLabel: 'AED 4.5M', location: { area: 'Downtown Dubai', emirate: 'Dubai' }, propertyType: 'apartment-maid', bedrooms: 2, bathrooms: 3, squareFt: 1800, completionYear: '2024', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Concierge', 'Valet', 'Maid Room'], status: 'for-sale', isFeatured: false },
        { title: 'Ajman Corniche Apt + Maid', slug: 'ajman-corniche-apt-maid', description: 'Sea-facing apartment with maid room on Ajman Corniche. Excellent value.', price: 750000, priceLabel: 'AED 750K', location: { area: 'Ajman Corniche', emirate: 'Ajman' }, propertyType: 'apartment-maid', bedrooms: 2, bathrooms: 2, squareFt: 1350, completionYear: '2025', completionStatus: 'off-plan', paymentPlan: { downPayment: 10, onCompletion: 50, description: '10/40/50' }, developer: developers[1]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Gym', 'Sea View', 'Maid Room'], status: 'for-sale', isFeatured: false },

        // ===== SEMI DETACHED =====
        { title: 'Dubai Hills Semi-Detached', slug: 'dubai-hills-semi-detached', description: 'Modern semi-detached villa in Dubai Hills Estate with park views.', price: 3200000, priceLabel: 'AED 3.2M', location: { area: 'Dubai Hills Estate', emirate: 'Dubai' }, propertyType: 'semi-detached', bedrooms: 4, bathrooms: 4, squareFt: 2500, completionYear: '2024', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Pool', 'Park', 'School', 'Mall Access'], status: 'for-sale', isFeatured: true },
        { title: 'Sharjah Semi-Detached Off-Plan', slug: 'sharjah-semi-detached-offplan', description: 'Affordable semi-detached home in Sharjah with flexible payment plans.', price: 1200000, priceLabel: 'AED 1.2M', location: { area: 'Aljada', emirate: 'Sharjah' }, propertyType: 'semi-detached', bedrooms: 3, bathrooms: 3, squareFt: 2000, completionYear: '2027', completionStatus: 'off-plan', paymentPlan: { downPayment: 10, onCompletion: 40, description: '10/50/40' }, developer: developers[1]._id, agent: agents[1]._id, images: [IMG], amenities: ['Pool', 'Park', 'Mosque', 'Retail'], status: 'for-sale', isFeatured: false },

        // ===== SUITES =====
        { title: 'Armani Hotel Suite', slug: 'armani-hotel-suite', description: 'Exclusive Armani-branded hotel suite in Burj Khalifa with iconic views.', price: 3800000, priceLabel: 'AED 3.8M', location: { area: 'Downtown Dubai', emirate: 'Dubai' }, propertyType: 'suite', bedrooms: 1, bathrooms: 1, squareFt: 850, completionYear: '2010', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Room Service', 'Spa', 'Pool', 'Concierge'], status: 'for-sale', isFeatured: true },
        { title: 'Five Palm Suite Rental', slug: 'five-palm-suite-rental', description: 'Luxury hotel suite for rent at FIVE Palm Jumeirah with beach club access.', price: 160000, priceLabel: 'AED 160K/yr', location: { area: 'Palm Jumeirah', emirate: 'Dubai' }, propertyType: 'suite', bedrooms: 1, bathrooms: 1, squareFt: 700, completionYear: '2017', completionStatus: 'ready-to-move', developer: developers[4]._id, agent: agents[1]._id, images: [IMG], amenities: ['Beach Club', 'Pool', 'Spa', 'Night Club'], status: 'for-rent', isFeatured: false },

        // ===== SKY MANSIONS =====
        { title: 'One Crescent Sky Mansion', slug: 'one-crescent-sky-mansion', description: 'Tri-level sky mansion at One Crescent on Palm Jumeirah. Absolute pinnacle of luxury.', price: 85000000, priceLabel: 'AED 85M', location: { area: 'Palm Jumeirah', emirate: 'Dubai' }, propertyType: 'sky-mansion', bedrooms: 7, bathrooms: 8, squareFt: 15000, completionYear: '2026', completionStatus: 'off-plan', paymentPlan: { downPayment: 30, onCompletion: 40, description: '30/30/40' }, developer: developers[4]._id, agent: agents[0]._id, images: [IMG], amenities: ['Private Elevator', 'Pool', 'Cinema', 'Wine Room', 'Helipad'], status: 'for-sale', isFeatured: true },

        // ===== VILLA + BASEMENT =====
        { title: 'Dubai Hills Villa + Basement', slug: 'dubai-hills-villa-basement', description: 'Spacious villa with full basement in Dubai Hills Estate. Extra entertainment and storage space.', price: 5800000, priceLabel: 'AED 5.8M', location: { area: 'Dubai Hills Estate', emirate: 'Dubai' }, propertyType: 'villa-basement', bedrooms: 5, bathrooms: 5, squareFt: 5200, completionYear: '2024', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[0]._id, images: [IMG], amenities: ['Pool', 'Basement', 'Garden', 'Gym', 'Cinema Room'], status: 'for-sale', isFeatured: false },
        { title: 'Mohammed Bin Rashid City Villa + Basement', slug: 'mbr-city-villa-basement', description: 'Premium villa with finished basement in MBR City District One.', price: 14000000, priceLabel: 'AED 14M', location: { area: 'MBR City', emirate: 'Dubai' }, propertyType: 'villa-basement', bedrooms: 6, bathrooms: 7, squareFt: 8000, completionYear: '2023', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[2]._id, images: [IMG], amenities: ['Pool', 'Basement', 'Lagoon', 'Gym', 'Staff Quarters'], status: 'for-sale', isFeatured: true },

        // ===== OFFICES =====
        { title: 'DIFC Office Suite', slug: 'difc-office-suite', description: 'Premium Grade-A office in DIFC with city views. Ideal for financial firms.', price: 4200000, priceLabel: 'AED 4.2M', location: { area: 'DIFC', emirate: 'Dubai' }, propertyType: 'office', bedrooms: 0, bathrooms: 2, squareFt: 1800, completionYear: '2020', completionStatus: 'ready-to-move', developer: developers[0]._id, agent: agents[2]._id, images: [IMG], amenities: ['Meeting Rooms', 'Parking', 'Concierge', 'Café'], status: 'for-sale', isFeatured: false },
        { title: 'Business Bay Office Rental', slug: 'business-bay-office-rental', description: 'Flexible office space for rent in Business Bay with metro access.', price: 95000, priceLabel: 'AED 95K/yr', location: { area: 'Business Bay', emirate: 'Dubai' }, propertyType: 'office', bedrooms: 0, bathrooms: 1, squareFt: 900, completionYear: '2018', completionStatus: 'ready-to-move', developer: developers[3]._id, agent: agents[1]._id, images: [IMG], amenities: ['Parking', 'Metro Access', 'Café'], status: 'for-rent', isFeatured: false },

        // ===== COMMERCIAL =====
        { title: 'JLT Retail Shop', slug: 'jlt-retail-shop', description: 'Ground-floor retail space in JLT with high footfall and lake views.', price: 2800000, priceLabel: 'AED 2.8M', location: { area: 'JLT', emirate: 'Dubai' }, propertyType: 'commercial', bedrooms: 0, bathrooms: 1, squareFt: 1200, completionYear: '2016', completionStatus: 'ready-to-move', developer: developers[2]._id, agent: agents[2]._id, images: [IMG], amenities: ['Parking', 'Lake View', 'Metro Access'], status: 'for-sale', isFeatured: false },
        { title: 'Silicon Oasis Warehouse Rental', slug: 'silicon-oasis-warehouse-rental', description: 'Warehouse and office combo for rent in Dubai Silicon Oasis free zone.', price: 180000, priceLabel: 'AED 180K/yr', location: { area: 'Dubai Silicon Oasis', emirate: 'Dubai' }, propertyType: 'commercial', bedrooms: 0, bathrooms: 2, squareFt: 5000, completionYear: '2015', completionStatus: 'ready-to-move', developer: developers[3]._id, agent: agents[0]._id, images: [IMG], amenities: ['Loading Bay', 'Office', 'Parking'], status: 'for-rent', isFeatured: false },
    ]);
    console.log(`${properties.length} properties created`);

    // --- Blog Posts ---
    const blogPosts = await BlogPost.insertMany([
        { title: 'Dubai Real Estate Market Trends 2026', slug: 'dubai-real-estate-market-trends-2026', content: 'Dubai\'s real estate market continues to show remarkable growth in 2026. With new developments, infrastructure projects, and favorable government policies, the emirate remains one of the top investment destinations globally. Key areas like Downtown Dubai, Dubai Marina, and emerging communities like Dubailand are seeing strong demand from both local and international buyers.\n\nThe off-plan segment has been particularly active, with developers offering attractive payment plans to entice buyers. Branded residences by luxury brands like Mercedes Benz, Bugatti, and Armani continue to command premium prices and attract high-net-worth individuals.', excerpt: 'An in-depth look at Dubai\'s booming real estate market and what to expect in 2026.', coverImage: IMG, category: 'Market Insights', tags: ['Dubai', 'Market Trends', '2026', 'Investment'] },
        { title: 'Top 5 Off-Plan Projects to Invest In', slug: 'top-5-off-plan-projects-to-invest-in', content: 'Off-plan properties in Dubai offer some of the best returns on investment. With flexible payment plans and lower entry prices, they are an excellent choice for first-time investors and seasoned buyers alike.\n\nHere are our top 5 picks for 2026:\n1. Creek Waters Residence by Emaar\n2. Binghatti Ghost in Business Bay\n3. Damac Islands Phase II\n4. Mercedes Benz Places\n5. Solvara 4 at Grand Polo Club\n\nEach of these projects offers unique value propositions from waterfront living to branded luxury experiences.', excerpt: 'Discover the best off-plan investment opportunities in Dubai for maximum returns.', coverImage: IMG, category: 'Investment Guide', tags: ['Off-Plan', 'Investment', 'Top Picks'] },
        { title: 'Guide to Buying Property in Dubai as a Foreigner', slug: 'guide-to-buying-property-in-dubai-as-a-foreigner', content: 'Dubai welcomes international property buyers with open arms. Foreigners can purchase freehold property in designated areas across Dubai, giving them full ownership rights.\n\nKey steps include:\n- Choose a reputable developer or agent\n- Understand the payment structure\n- Get DLD (Dubai Land Department) registration\n- Consider mortgage options if needed\n- Factor in service charges and maintenance fees\n\nWith no property tax and strong rental yields averaging 6-8%, Dubai remains an attractive investment destination for global buyers.', excerpt: 'Everything you need to know about purchasing property in Dubai as an international buyer.', coverImage: IMG, category: 'Buyer Guide', tags: ['Foreign Buyers', 'Guide', 'Dubai'] },
        { title: 'Branded Residences: The Future of Luxury Living', slug: 'branded-residences-future-of-luxury-living', content: 'Branded residences are redefining luxury living in Dubai. World-renowned brands like Bugatti, Mercedes Benz, Armani, and Versace are partnering with top developers to create exclusive living experiences.\n\nThese residences offer:\n- Bespoke interior design by the brand\n- Five-star hotel-style amenities\n- Exclusive owners-only facilities\n- Potential for higher appreciation and rental premiums\n\nDubai leads the world in branded residence development, with over 50 projects planned or completed.', excerpt: 'How luxury brands are transforming Dubai\'s residential landscape.', coverImage: IMG, category: 'Luxury Living', tags: ['Branded Residences', 'Luxury', 'Lifestyle'] },
        { title: 'Dubai Golden Visa Through Property Investment', slug: 'dubai-golden-visa-through-property-investment', content: 'The UAE Golden Visa program allows property investors to obtain long-term residency. By investing AED 2 million or more in real estate, you can qualify for a 10-year renewable visa.\n\nBenefits include:\n- 10-year residency for you and your family\n- No sponsor required\n- Ability to sponsor domestic workers\n- Multiple entries and exits without restrictions\n- Access to UAE banking and financial services\n\nThis has made Dubai property investment even more attractive to international buyers seeking both returns and residency.', excerpt: 'Learn how property investment can secure your UAE Golden Visa.', coverImage: IMG, category: 'Visa & Immigration', tags: ['Golden Visa', 'Investment', 'Residency'] },
    ]);
    console.log(`${blogPosts.length} blog posts created`);

    console.log('\n✅ Seed complete!');
    process.exit(0);
}

seed().catch((err) => {
    console.error('Seed error:', err);
    process.exit(1);
});
